tests/winetricks-test: fix shellcheck issues

diff --git a/tests/winetricks-test b/tests/winetricks-test
--- a/tests/winetricks-test
+++ b/tests/winetricks-test
@@ -65,19 +65,19 @@ errors=0
 
 fail()
 {
-    echo FAIL: $@
-    errors=$(expr $errors + 1)
+    echo "FAIL: $*"
+    errors=$((errors + 1))
 }
 
 pass()
 {
-    echo PASS: $@       
-    passes=$(expr $passes + 1)
+    echo "PASS: $*"
+    passes=$((passes + 1))
 }
 
 w_die()
 {
-    echo "$@"
+    echo "$*"
 
     exit 1
 }
@@ -154,15 +154,15 @@ case "$OS" in
     ;;
 esac
 
-srcdir=$(dirname $0)
-srcdir=$(cd $srcdir; pwd)
+srcdir=$(cd "$(dirname "$0")" || w_die "Could not cd to $(dirname "$0")" ; pwd)
 
 test_speed()
 {
-    if ! w_time sh winetricks nocrashdialog $1 > foo.log
+    if ! w_time sh winetricks nocrashdialog "$1" > foo.log
     then
         fail "winetricks $1 returned status $?"
     fi
+    # shellcheck disable=SC2046
     if test $(wc -l < foo.log) -lt 5
     then
         fail "winetricks $1 returned too few lines"
@@ -174,8 +174,9 @@ test_speed()
     else
         seconds=$(awk '/real/ {print $2}' < time.log | sed 's/\..*//')
     fi
-    echo test_speed: winetricks $1 took $seconds seconds
+    echo "test_speed: winetricks $1 took $seconds seconds"
     # Longest runtime as of 11 Dec 2010 is 5 seconds on an e8400 with cygwin
+    # shellcheck disable=SC2086
     if test $seconds -gt 7
     then
         fail "test_speed: winetricks $1 took $seconds seconds"
@@ -190,18 +191,18 @@ test_app_checksums()
         windir="$($WINE cmd /c echo "%windir%" | cut -c 4- | tr -d '\015')"
         progdir="$($WINE cmd /c echo "%ProgramFiles%" | cut -c 4- | tr -d '\015')"
 
-        cd "$DRIVE_C"
+        cd "$DRIVE_C" || w_die "Could not cd to $DRIVE_C"
         # Fix up the filenames, which can differ between Windows versions/Wine:
         # FIXME: we need a way to guarantee that all _original_ .sha1sums are the same.
         # Preferably generated under 32-bit wine, so that we don't need a really complex sed
         # substitution here...
-        sed -e "s!Program\ Files/!/$progdir/!" -e "s!/windows/!/$windir/!" < "$srcdir/winetricksverify.d/$app.sha1sum" > $app.sha1sum.tmp
-        if ! sha1sum -c $app.sha1sum.tmp
+        sed -e "s!Program\ Files/!/$progdir/!" -e "s!/windows/!/$windir/!" < "$srcdir/winetricksverify.d/$app.sha1sum" > "$app.sha1sum.tmp"
+        if ! sha1sum -c "$app.sha1sum.tmp"
         then
             fail "test_app_checksum $app !"
         fi
-        rm $app.sha1sum.tmp
-        cd $srcdir
+        rm "$app.sha1sum.tmp"
+        cd "$srcdir" || w_die "Could not cd into $srcdir"
     fi
 }
 
@@ -215,20 +216,19 @@ total_df()
 test_app()
 {
     app=$1
-    _errors_before=$errors
 
     # Watch transient disk space
     DF_START=$(total_df)
-    if test -d "$W_CACHE"/$app
+    if test -d "$W_CACHE/$app"
     then
-        DU_CACHE_START=$(du -s "$W_CACHE"/$app | awk '{print $1}')
+        DU_CACHE_START=$(du -s "$W_CACHE/$app" | awk '{print $1}')
     else
         DU_CACHE_START=0
     fi
     touch df-daemon
     (set +x; while test -f df-daemon; do total_df; sleep 1; done ) > df-during.log &
 
-    test_command --verify $app
+    test_command --verify "$app"
     test_app_checksums
 
     # Post install:
@@ -237,7 +237,7 @@ test_app()
     allcodecs) ;;
     *)
         sh winetricks -q list-installed > list-installed.out
-        if ! grep -w $app list-installed.out
+        if ! grep -w "$app" list-installed.out
         then
             fail "test app $app not installed after install?"
         fi
@@ -247,28 +247,27 @@ test_app()
     # Cleanup..
     rm df-daemon
     # Total max disk usage = max df change plus any initial blocks in cache
-    DF_MIN=$(cat df-during.log | awk '{ if (min == "" || $1 < min) min=$1; } END {print min}' )
-    DF_DIFF=$(expr $DF_START - $DF_MIN)
-    TOTAL=$(expr $DF_DIFF + $DU_CACHE_START)
+    DF_MIN=$(awk '{ if (min == "" || $1 < min) min=$1; } END {print min}' < df-during.log )
+    DF_DIFF=$((DF_START - DF_MIN))
+    TOTAL=$((DF_DIFF + DU_CACHE_START))
     echo "test_app: ${app}: max_disk $TOTAL blocks."
-
-    TOTAL_MB=$(expr $TOTAL / 1024)
+    TOTAL_MB=$((TOTAL / 1024))
     mkdir -p measurements
-    echo "${app}:size_MB=${TOTAL_MB},time_sec=${seconds}" >> measurements/$app.dat
+    echo "${app}:size_MB=${TOTAL_MB},time_sec=${seconds}" >> "measurements/$app.dat"
 }
 
 test_command()
 {
-    command=$@
-    _errors_before=$errors
+    command="$*"
+    _command_dash="$(echo "$command" | tr " " "-")"
 
-    export WINEPREFIX=$WINE_PREFIXES/$(echo $@ | tr " " "-")
+    export WINEPREFIX="$WINE_PREFIXES/$_command_dash"
     DRIVE_C="$WINEPREFIX/dosdevices/c:"
 
     # always use a clean $WINEPREFIX
-    if test -d $WINEPREFIX
+    if test -d "$WINEPREFIX"
     then
-        rm -rf $WINEPREFIX
+        rm -rf "$WINEPREFIX"
     fi
 
     # Isolate us from the user's home directory
@@ -278,14 +277,17 @@ test_command()
     if [ "$EXPECT_FAIL" = "yes" ]
     then
         # A success is failure:
-        sh winetricks --no-isolate -q nocrashdialog $command && fail "$@ succeeded, should have failed"
+        # shellcheck disable=SC2086
+        sh winetricks --no-isolate -q nocrashdialog $command && fail "$* succeeded, should have failed"
+    # FIXME: shellcheck disabling doesn't work here (if clause related). Need to file bug:
+    # shellcheck disable=SC2086
     elif ! w_time sh winetricks --no-isolate -q nocrashdialog $command
     then
         rm df-daemon
         fail "test_command $command failed!"
         return
     else
-        echo "winetricks $@ completed"
+        echo "winetricks $* completed"
     fi
     if ! test -f time.log
     then
@@ -312,11 +314,12 @@ test_command()
     killall notepad.exe          # Arcania-Gothic4 and others
 
     echo "Checking for dangling processes!"
+    # shellcheck disable=SC2009
     ps augxw | grep \\.exe
     "$WINESERVER" -w
     echo "Wineserver done."
 
-    pass $@
+    pass "$@"
 }
 
 test_custom_verbs()
@@ -441,10 +444,10 @@ test_dlls()
         exit 1
     fi
     sort -u < dlls.log | fgrep -w -v -f manual.log | egrep -v "$BLACKLIST" > dlls.verbs
-    for a in $(cat dlls.verbs)
-    do
-        test_app $a
-    done
+
+    while IFS= read -r line; do
+        test_app "$line"
+    done < dlls.verbs
 }
 
 test_dotnet()
@@ -480,10 +483,9 @@ test_manual_dlls()
         exit 1
     fi
     cat dlls.log manual.log | sort | uniq -c | awk '$1 == 2 {print $2}' | egrep -v "$BLACKLIST" > dlls.verbs
-    for a in $(cat dlls.verbs)
-    do
-        test_app $a
-    done
+    while IFS= read -r line; do
+        test_app "$line"
+    done < dlls.verbs
 }
 
 test_install_cached_or_download()
@@ -499,10 +501,10 @@ test_install_cached_or_download()
     if true
     then
         # Split into two, only do half
-        nverbs=$(cat ticd.verbs | wc -l)
-        firsthalf=$(expr $nverbs / 2 + 1)
-        sed ${firsthalf}',$d' < ticd.verbs > ticd-1.verbs
-        sed '1,'${firsthalf}d   < ticd.verbs > ticd-2.verbs
+        nverbs=$(wc -l < ticd.verbs )
+        firsthalf=$((nverbs / 2 + 1))
+        sed "${firsthalf}"',$d' < ticd.verbs > ticd-1.verbs
+        sed '1,'"${firsthalf}"d   < ticd.verbs > ticd-2.verbs
         VERBS=$(cat ticd-1.verbs)
     else
         VERBS=$(cat ticd.verbs)
@@ -510,7 +512,7 @@ test_install_cached_or_download()
 
     for a in $VERBS
     do
-        test_app $a
+        test_app "$a"
     done
     sh winetricks list-cached | sort > cached.txt
     # Verbs that are just wrappers around others don't detect cache/install
@@ -518,7 +520,7 @@ test_install_cached_or_download()
     # Verbs that are just informative placeholders don't ever download (gecko).
     # And some verbs (gecko110) don't usually install for other reasons.
     BLACKLIST_CACHE="allfonts\|cjkfonts\|allcodecs\|gecko\|gecko110\|fontfix"
-    cat ticd.verbs | egrep -vw "$BLACKLIST_CACHE" > download.txt
+    egrep -vw "$BLACKLIST_CACHE" ticd.verbs > download.txt
     comm -23 download.txt cached.txt > download-but-not-cached.txt
     echo "Supposedly downloadable"
     cat download.txt
@@ -526,6 +528,7 @@ test_install_cached_or_download()
     cat cached.txt
     echo "Downloadable but not cached"
     cat download-but-not-cached.txt
+    # shellcheck disable=SC2046
     if test $(wc -l < download-but-not-cached.txt) != 0
     then
         fail "test_install_cached_or_download: asked to install all downloadable apps, but some not listed as cached afterwards"
@@ -540,8 +543,9 @@ test_quick()
     export W_CACHE="$cache"
     for a in $QUICKCHECK
     do
-       rm -rf "$WINE_PREFIXES"/$a
-       test_app $a
+        # shellcheck disable=SC2115
+        rm -rf "$WINE_PREFIXES/$a"
+        test_app "$a"
     done
 
     # And test all the automatically-downloadable dlls
