winetricks: add dotnet11 tests, optionally enabled with --verify
git-svn-id: https://winetricks.googlecode.com/svn/trunk@1163 98bf863f-ac88-fb5c-4855-c94565d26d3c

diff --git a/src/winetricks b/src/winetricks
--- a/src/winetricks
+++ b/src/winetricks
@@ -499,6 +499,46 @@ winetricks_wget_progress()
     esac
 }
 
+w_dotnet_verify()
+{
+    case $1 in
+        dotnet11) version="1.1" ;;
+        *) echo error ; exit 1 ;;
+    esac
+            w_call dotnet_verifier
+            # FIXME: The logfile may be useful somewhere (or at least print the location)
+            w_ahk_do "
+                SetTitleMatchMode, 2
+                ; FIXME; this only works the first time? Check if it's already verified somehow..
+                run, netfx_setupverifier.exe /q:a /c:"setupverifier2.exe"
+                winwait, Verification Utility
+                ControlClick, Button1
+                Control, ChooseString, NET Framework $version, ComboBox1
+                ControlClick, Button1 ; Verify
+                loop, 60
+                {
+                    sleep 1000
+                    process, exist, setupverifier2.exe
+                    dn_pid=%ErrorLevel%
+                    if dn_pid = 0
+                    {
+                        break
+                    }
+                    ifWinExist, Verification Utility, Product verification failed
+                    {
+                        process, close, setupverifier2.exe
+                        exit 1
+                    }
+                    ifWinExist, Verification Utility, Product verification succeeded
+                    {
+                        process, close, setupverifier2.exe
+                        break
+                    }                    
+                }
+            "
+            dn_status=$?
+}
+
 # Download a file
 # Usage: w_download_to packagename url [sha1sum [filename [cookie jar]]]
 # Caches downloads in winetrickscache/$packagename
@@ -2013,9 +2053,6 @@ w_do_call()
             . "$postfile"
         fi
 
-        # Clean up after this verb
-        test "$W_OPT_NOCLEAN" = 1 || rm -rf "$W_TMP"
-
         # Verify install
         if test "$installed_exe1" || test "$installed_file1"
         then
@@ -2024,6 +2061,16 @@ w_do_call()
                 w_die "$1 install completed, but installed file $_W_file_unix not found"
             fi
         fi
+
+        # If the user specified --verify, also run gui tests:
+        if test "$WINETRICKS_VERIFY" = 1 && type verify_$cmd 2> /dev/null
+        then
+            w_try verify_$cmd
+        fi
+
+        # Clean up after this verb
+        test "$W_OPT_NOCLEAN" = 1 || rm -rf "$W_TMP"
+
         # Calling subshell must explicitly propagate error code with exit $?
     ) || exit $?
 }
@@ -3775,6 +3822,7 @@ Options:
 -q, --unattended      Don't ask any questions, just install automatically
 -r, --ddrescue        Retry hard when caching scratched discs
     --showbroken      Even show verbs that are currently broken in wine
+    --verify          Run (automated) GUI tests for verbs, if available
 -v, --verbose         Echo all commands as they are executed
 -h, --help            Display this message and exit
 -V, --version         Display version and exit
@@ -3805,6 +3853,7 @@ winetricks_handle_option()
     -q|--unattended) winetricks_set_unattended 1 ;;
     -v|--verbose) WINETRICKS_OPT_VERBOSE=1; set -x ;;
     -V|--version) winetricks_print_version ; exit 0;;
+    --verify) WINETRICKS_VERIFY=1 ;;
     -h|--help) winetricks_usage ; exit 0 ;;
     --isolate) WINETRICKS_OPT_SHAREDPREFIX=0 ;;
     --no-isolate) WINETRICKS_OPT_SHAREDPREFIX=1 ;;
@@ -4792,6 +4841,11 @@ load_dotnet11()
     else
         WINEDLLOVERRIDES="regsvcs.exe=b" w_try "$WINE" dotnetfx.exe
     fi
+}
+
+verify_dotnet11()
+{
+    w_dotnet_verify dotnet11
 }
 
 #----------------------------------------------------------------
