winetricks_detect_gui: prefer kdialog when running on KDE
Also make it configurable by passing --gui

diff --git a/src/winetricks b/src/winetricks
--- a/src/winetricks
+++ b/src/winetricks
@@ -3520,43 +3520,41 @@ winetricks_early_wine_arch()
 
 winetricks_detect_gui()
 {
-    if test "${XDG_CURRENT_DESKTOP}" != "KDE"; then
-        if test -x "$(command -v zenity 2>/dev/null)"; then
-            WINETRICKS_GUI=zenity
-            WINETRICKS_GUI_VERSION="$(zenity --version)"
-            WINETRICKS_MENU_HEIGHT=500
-            WINETRICKS_MENU_WIDTH=1010
-        elif test -x "$(command -v kdialog 2>/dev/null)"; then
-            echo "Zenity not found!  Using kdialog as a substitute."
+    if [ -n "$1" ]; then
+        if [ "$1" = "kdialog" ] && test -x "$(command -v kdialog 2>/dev/null)"; then
             WINETRICKS_GUI=kdialog
             WINETRICKS_GUI_VERSION="$(kdialog --version)"
-        else
-            echo "No arguments given, so tried to start GUI, but zenity or kdialog not found."
-            echo "Please install zenity or kdialog if you want a graphical interface, or "
-            echo "run with --help for more options."
-            exit 1
-        fi
-    elif test "${XDG_CURRENT_DESKTOP}" = "KDE"; then
-        if test -x "$(command -v kdialog 2>/dev/null)"; then
-            WINETRICKS_GUI=kdialog
-            WINETRICKS_GUI_VERSION="$(kdialog --version)"
-        elif test -x "$(command -v zenity 2>/dev/null)"; then
-            echo "kdialog not found!  Using zenity as a substitute."
+        elif [ "$1" = "zenity" ] || [ "$1" = "--gui" ] && test -x "$(command -v zenity 2>/dev/null)"; then
             WINETRICKS_GUI=zenity
             WINETRICKS_GUI_VERSION="$(zenity --version)"
             WINETRICKS_MENU_HEIGHT=500
             WINETRICKS_MENU_WIDTH=1010
         else
-            echo "No arguments given, so tried to start GUI, but kdialog or zenity not found."
-            echo "Please install kdialog or zenity if you want a graphical interface, or "
-            echo "run with --help for more options."
+            echo "Invalid argument for --gui"
+            echo "Valid options are 'zenity' and 'kdialog'"
             exit 1
         fi
+    elif [ "${XDG_CURRENT_DESKTOP}" = "KDE" ] && test -x "$(command -v kdialog 2>/dev/null)"; then
+        WINETRICKS_GUI=kdialog
+        WINETRICKS_GUI_VERSION="$(kdialog --version)"
+    elif test -x "$(command -v zenity 2>/dev/null)"; then
+        WINETRICKS_GUI=zenity
+        WINETRICKS_GUI_VERSION="$(zenity --version)"
+        WINETRICKS_MENU_HEIGHT=500
+        WINETRICKS_MENU_WIDTH=1010
+    elif test -x "$(command -v kdialog 2>/dev/null)"; then
+        WINETRICKS_GUI=kdialog
+        WINETRICKS_GUI_VERSION="$(kdialog --version)"
+    else
+        echo "No arguments given, so tried to start GUI, but neither zenity"
+        echo "nor kdialog were found. Please install one of them if you want"
+        echo "a graphical interface, or run with --help for more options."
+        exit 1
     fi
 
     # Print zenity/dialog version info for debugging:
     if [ -z "${WINETRICKS_SUPER_QUIET}" ] ; then
-       echo "winetricks GUI enabled, using ${WINETRICKS_GUI} ${WINETRICKS_GUI_VERSION}"
+       echo "winetricks GUI enabled, using ${WINETRICKS_GUI} ${WINETRICKS_GUI_VERSION##kdialog }"
     fi
 }
 
@@ -5765,6 +5763,7 @@ Options:
     --country=CC      Set country code to CC and don't detect your IP address
 -f, --force           Don't check whether packages were already installed
     --gui             Show gui diagnostics even when driven by commandline
+    --gui=OPT         Set OPT to kdialog or zenity to override GUI engine
     --isolate         Install each app or game in its own bottle (WINEPREFIX)
     --self-update     Update this application to the last version
     --update-rollback Rollback the last self update
@@ -5806,7 +5805,7 @@ winetricks_handle_option()
     case "$1" in
         --country=*) W_COUNTRY="${1##--country=}" ;;
         -f|--force) WINETRICKS_FORCE=1;;
-        --gui) winetricks_detect_gui;;
+        --gui*) winetricks_detect_gui "${1##--gui=}";;
         -h|--help) winetricks_usage ; exit 0 ;;
         --isolate) WINETRICKS_OPT_SHAREDPREFIX=0 ;;
         -k|--keep_isos) WINETRICKS_OPT_KEEPISOS=1 ;;
@@ -23289,7 +23288,9 @@ if ! test "${WINETRICKS_LIB}"; then
 
             # GUI case
             # No non-option arguments given, so read them from GUI, and loop until user quits
-            winetricks_detect_gui
+            if [ ${WINETRICKS_GUI} = "none" ]; then
+                winetricks_detect_gui
+            fi
             winetricks_detect_sudo
             test -z "${WINETRICKS_ISO_MOUNT}" && winetricks_detect_iso_mount
             while true; do
